### ISSUE TITLE
Deploy examples live for easier testing

### ISSUE THREAD

**Issue by corneliusroemer** [AnswerDotAI/fasthtml-example#15]
It would be great if examples were automatically deployed to somewhere like railway or vercel to be able to see them live - this would also make testing that they still work with the latest version of fasthtml easier.

**Comment by jph00** [comment]
Agreed - that's what https://fasthtml.gallery is all about! We'll be adding more examples there over time. It'll be moved to the answerdotai org soon, but for now it's at https://github.com/Isaac-Flath/FastHTML-Gallery .
