### ISSUE TITLE
Wrong sakura CSS link

### ISSUE THREAD

**Issue by leandermaerkisch** [AnswerDotAI/fasthtml-example#16]
In the for [web devs docs](https://docs.fastht.ml/tutorials/quickstart_for_web_devs.html#css-files-and-inline-styles
) the following sakura css references are given.

![image](https://github.com/user-attachments/assets/e1538d49-49e4-45f3-9e77-c1e0845f33c3)

When using it out of the box, does not work
```
INFO:     127.0.0.1:64486 - "GET /assets/normalize.min.css HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:64487 - "GET /assets/sakura.css HTTP/1.1" 404 Not Found
```

The trick is to use the full url

```
Link(rel='stylesheet', href='https://unpkg.com/sakura.css/css/normalize.min.css', type='text/css'),
Link(rel='stylesheet', href='https://unpkg.com/sakura.css/css/sakura.css', type='text/css'),
```

It would be great to update the docs to make life easier for starters. Happy contribute it if you tell me where the docs reside!

**Comment by jph00** [comment]
You'll need to copy the files into your assets dir (if not using a cdn).
