### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by rbavery** [AnswerDotAI/fasthtml-example#3]
[FastHTML Examples Repo on GitHub](https://github.com/AnswerDotAI/fasthtml-examples)

referenced here: https://docs.fastht.ml/#next-steps

**Comment by gkteco** [comment]
Is this the link that is supposed to be referenced? https://docs.fastht.ml/tutorials/by_example.html#full-example-3---chatbot-example-with-daisyui-components

**Comment by johnowhitaker** [comment]
It should be https://github.com/AnswerDotAI/fasthtml-example (was examples plural, now fixed)
