### ISSUE TITLE
Chess are not working

### ISSUE THREAD

**Issue by Antunees** [AnswerDotAI/fasthtml-example#52]
I needed install python-fasthtml manually and after this, i get this error:
```
root@0e3a461ba531:/# python3 main.py 
Traceback (most recent call last):
  File "//main.py", line 21, in <module>
    css = Style(
NameError: name 'Style' is not defined

```

**Comment by johnowhitaker** [comment]
Thanks, I've changed the import, I'm not sure if that example is a work in progress or finished but the change at least resolves this issue.
