### ISSUE TITLE
counter-rsjs.py (with utils.py) error: name 'unqid' is not defined

### ISSUE THREAD

**Issue by dimplast** [AnswerDotAI/fasthtml-example#53]
i try to use
fasthtml-example/htmx/counter-rsjs.py 
with
fasthtml-example/htmx/utils.py

fasthtml python-fasthtml==0.6.12

and i get error
site-packages\fasthtml\components.py", line 79, in ft_html
    if auto_id and not id: id = unqid()
                                ^^^^^
NameError: name 'unqid' is not defined

**Comment by johnowhitaker** [comment]
It's defined in fasthtml now, I think there was a missing import briefly, fixed in https://github.com/AnswerDotAI/fasthtml/commit/31fdb75e7e33dab0ba1389e233aaecaec6fa0496
