### ISSUE TITLE
Question about variable scoping

### ISSUE THREAD

**Issue by DallanQ** [AnswerDotAI/fasthtml-example#9]
In the [chatbot example](https://github.com/AnswerDotAI/fasthtml-example/blob/main/02_chatbot/basic.py) the messages variable is declared at the script level. Does that mean that all requests would share the same set of messages, or is FastHTML doing something to limit the messages scope to a user session somehow? I'm trying to understand how FastHTML works under the hood. Thank you. The framework looks interesting.

**Comment by jph00** [comment]
This example shares the messages across requests to keep it simple.
